FROM node:10.14-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ["package.json", "yarn.lock", "./"]
RUN yarn
COPY . ./
CMD ["yarn", "build"]

#FROM nginx:stable-alpine
#COPY --from=build /app/server/build /usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]

FROM node:10.14-alpine
RUN yarn global add serve
WORKDIR /app
COPY --from=build /app/server/ .
EXPOSE 3000
CMD ["serve", "-p", "3000", "-s", "./build"]
