version: '3'
services:
  myapp-front:
    image: myapp-front
    build:
        context: .
        dockerfile: Dockerfile.prod
    ports:
      - 3000:3000      
    depends_on:
      - myapp-back
  myapp-back:
    image: myapp-back
    build: ./server
    ports:
      - 3001:3001